# based on https://github.com/peaceiris/actions-hugo
name: update main

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 */6 * * *"  # 分 时 日 月 周

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes recursively
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
          lfs: true              # download Git-LFS files

      - name: Use Python3
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true  #  need extended version to support SASS/SCSS

      - name: Build
        run: hugo --minify --debug --printUnusedTemplates

      # 自动构建出的 pages 目前有问题，mermaid/music 等 shortcodes 无法正常加载，先不 push
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: yuanque.github.io
